name: Create release notes
description: |
  Extracts release notes for current tag from CHANGELOG.md and writes them to a file called RELEASE.md.
  It is assumed that a header for RELEASE.md is found in the file RELEASE_HEAD.md.
inputs:
  version:
    description: 'Version number to search for in CHANGELOG.md (default: use tag without leading v)'
    required: false
    default: <tag version>
  begin-pattern:
    description: Sed pattern to find heading with correct version in CHANGELOG.md
    required: false
    default: '/^## \\[${RELEASE_VERSION}\\]/'
  end-pattern:
    description: Sed pattern to find next heading in CHANGELOG.md that does not belong to this version anymore
    required: false
    default: '/^## /'
  link-pattern:
    description: Grep pattern to find footnote-style compare link for this version (optional)
    required: false
    default: '^\\[${RELEASE_VERSION}\\]:'
  chop:
    description: 'Number of lines to chop from end of matching part of CHANGELOG.md'
    required: false
    default: '2'
  working-directory:
    description: 'Path to folder where CHANGELOG.md and RELEASE_HEAD.md can be found and where RELEASE.md should be placed'
    required: false
    default: '.'
runs:
  using: "composite"
  steps:
    - name: Set RELEASE_VERSION
      shell: bash
      run: >
        if [ "${{ inputs.version }}" = "<tag version>" ]; then
          RELEASE_VERSION_TEMP=${GITHUB_REF#refs/*/};
          echo "RELEASE_VERSION=${RELEASE_VERSION_TEMP#v}" >> $GITHUB_ENV;
        else
          echo "RELEASE_VERSION=${{ inputs.version }}" >> $GITHUB_ENV;
        fi
    - name: Print RELEASE_VERSION variable to be used in sed/grep patterns
      shell: bash
      run: echo "\$RELEASE_VERSION = $RELEASE_VERSION"
    - name: Start RELEASE.md with copy of RELEASE_HEAD.md
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        cp RELEASE_HEAD.md RELEASE.md
        printf "\n" >> RELEASE.md
        echo "Created release notes at `realpath RELEASE.md`"
    - name: Extract changelog for release version
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      # explanation of sed command:
      # 1. select lines between begin-pattern and end-pattern
      # 2. invert this selection
      # 3. delete it
      # => only selection is remaining in stream
      run: |
        echo "Pattern used for sed: ${{ inputs.begin-pattern }},${{ inputs.end-pattern }} ! d"
        sed -e "${{ inputs.begin-pattern }},${{ inputs.end-pattern }} ! d" CHANGELOG.md | head -n -${{ inputs.chop }} >> RELEASE.md
        printf "\n" >> RELEASE.md
    - name: Extract compare link for release version if it exists
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        grep "${{ inputs.link-pattern }}" CHANGELOG.md >> RELEASE.md
