on:
  push:
    tags: ['v*']

jobs:
  build:
    name: Create release for this action (with this action :D)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
      # use GitHub CLI to create release
      # see https://cli.github.com/manual/gh_release_create
      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: >
          gh release create
          -d
          -F RELEASE.md
          -t "Version $RELEASE_VERSION"
          ${GITHUB_REF#refs/*/}
