on:
  push:
    branches: [ main ]

jobs:
  build-first:
    name: Create release notes for first version in changelog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: CSchoel/release-notes-from-changelog@v0.1.8
        with:
          version: 0.1.0
          end-pattern: 'and \`RELEASE_HEAD.md\`'
      - run: cat RELEASE.md
  build-pattern:
    name: Uses explicit start and end pattern
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: CSchoel/release-notes-from-changelog@v0.1.8
        with:
          version: 0.1.5
          start-pattern: '^### Fixed'
          end-pattern: '^##'
      - run: cat RELEASE.md
