on:
  push:
    branches: [ main ]

jobs:
  build-first:
    name: Create release notes for first version in changelog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: CSchoel/release-notes-from-changelog@v1.1
        with:
          version: 0.1.0
          end-pattern: '$'
          chop: 0
      - run: cat RELEASE.md
  build-pattern:
    name: Uses explicit begin and end pattern
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: CSchoel/release-notes-from-changelog@v1.1
        with:
          version: 0.1.5
          begin-pattern: '/^### Fixed/'
          end-pattern: '/^##/'
      - run: cat RELEASE.md
  build-headpath:
    name: Uses the input variable head-path
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: subdir
      - uses: CSchoel/release-notes-from-changelog@v1.1
        with:
          version: 1.1.0
          head-path: subdir/RELEASE_HEAD.md
      - run: cat RELEASE.md
